### ISSUE TITLE
Yank for minimal-versions

### ISSUE THREAD

**Issue by kornelski** [Kimundi/rustc-version-rs#38]
I'm hoping someday Rust will work with minimal version resolution (-Z minimal-versions). Currently `rustc_version` is an obstacle, because it required semver 0.1, which doesn't compile with Rust 1.x.

Can you yank it the prehistoric versions? 

```bash
cargo yank --vers 0.1.0
cargo yank --vers 0.1.1
cargo yank --vers 0.1.2
cargo yank --vers 0.1.3
cargo yank --vers 0.1.4
cargo yank --vers 0.1.5
cargo yank --vers 0.1.6
cargo yank --vers 0.1.7
```

**Comment by djc** [comment]
Done!

**Comment by not-an-aardvark** [comment]
Hi folks -- for what it's worth, I think yanking these versions had the effect of breaking a few libraries, such as [ocl](https://github.com/cogciprocate/ocl/issues/202), which specifies `rustc_version = "0.1"`. While binaries with lockfiles are unaffected, this is preventing new usage of that library (see e.g. [here](https://www.reddit.com/r/rust/comments/lyj1sj/is_the_ocl_crate_unmaintained)).

I'm a bit confused by the reasoning in the OP:

> Currently rustc_version is an obstacle [to minimal-versions], because it required semver 0.1, which doesn't compile with Rust 1.x.

I'm not very familiar with the minimal-versions proposal and just skimmed the [Cargo issue](https://github.com/rust-lang/cargo/issues/5657) for it now. That said, my understanding of the problem is:

* Certain old versions of `rustc_version` depended on `semver@0.1`
* Some versions on the `semver@0.1.x` release line didn't compile with Rust 1.0, while other versions did compile (which is why it was possible to use old versions of `rustc_version` at all).
* As a result, depending on old versions of `rustc_version` would have caused problems with the cargo minimal-versions feature.

But yanking old versions of `rustc_version` breaks packages that were successfully using old versions of `rustc_version`, which seems counterproductive. It seems like it would be better to only yank the old versions of packages that were already broken -- this would solve the minimal-versions problem without breaking peoples' builds.

In this case, that would mean yanking old versions of `semver` rather than `rustc_version`, which was conveniently [already done a few days ago](https://github.com/steveklabnik/semver/issues/229). So I think the old versions of `rustc_version` (or at least `rustc_version@0.1.7`) should be unyanked -- this would fix packages that depend on those versions, without causing any problems for the minimal-versions feature.

**Comment by djc** [comment]
Sounds compelling to me, and sorry that my yanking has caused trouble for you! @kornelski do you agree this makes sense? Presumably unyanking 0.1.7 only would be good enough?

**Comment by kornelski** [comment]
Yup. 

Sorry for the breakage. I didn't expect that such old version was still in use.

**Comment by djc** [comment]
I have unyanked 0.1.7. If anyone has a use case of unyanking any of the older versions, let me know.

**Comment by not-an-aardvark** [comment]
Thanks!
